import { ThemeProvider } from "next-themes";
import { trTR } from "@clerk/localizations";

import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider, useUser } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { Provider } from "@/components/graphql-provider";
import { ShopbagProvider } from "@/components/context/ShopbagContext";

export const metadata: Metadata = {
   title: "Kafe Sipariş Sistemi",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning={true}>
         <body className="font-poppins">
            <ClerkProvider appearance={{ elements: { footer: "hidden" } }} localization={trTR}>
               <ShopbagProvider>
                  <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                     <Provider>{children}</Provider>
                     <Toaster />
                  </ThemeProvider>
               </ShopbagProvider>
            </ClerkProvider>
         </body>
      </html>
   );
}
